DROP INDEX `UQ_ACC_NO` ON `AC_ACCOUNT`;
DROP INDEX `INX_OBJ_NO` ON `AC_ACCOUNT`;
DROP INDEX `UQ_COMMAND_NO` ON ` AC_TRANSACTION`;
DROP INDEX `INX_TRADE_NO` ON ` AC_TRANSACTION`;
DROP INDEX `INX_TRANSACTION_CTIME` ON ` AC_TRANSACTION`;
DROP INDEX `UQ_TRAN_ID_ACC_NO` ON `AC_SEQUENTIAL `;
DROP INDEX `INX_SEQUENTIAL_CTIME` ON `AC_SEQUENTIAL `;

DROP TABLE `AC_ACCOUNT`;
DROP TABLE ` AC_TRANSACTION`;
DROP TABLE `AC_SEQUENTIAL `;

CREATE TABLE `AC_ACCOUNT` (
`ID` numeric NOT NULL COMMENT '主键',
`ACCOUNT_NO` varchar(30) NOT NULL DEFAULT '' COMMENT '账户号',
`ACCOUNT_NAME` varchar(255) NOT NULL COMMENT '账户名称',
`ACCOUNT_TYPE` varchar(8) NOT NULL COMMENT '账户类型',
`BALANCE` numeric(20,0) NOT NULL COMMENT '余额',
`CURRENCY` char(1) NOT NULL COMMENT '币种(1、人民币 、积分 3、代金券 4、美元 5、台币)',
`OVERDRAFT` char(1) NOT NULL COMMENT '是否可透支，true 可透支，false 不可透支',
`BALANCE_OF_DIRECTION` char(1) NOT NULL COMMENT '借贷类型(D:debit - 借记账户， C:credit - 贷记账户)',
`ACCOUNTING_SUBJECTS` varchar(10) NOT NULL COMMENT '会计科目',
`ACCOUNT_LEVEL` char(1) NOT NULL COMMENT '账户级别',
`STATUS` char(1) NOT NULL COMMENT '账户状态: norm - 正常， freeze - 冻结 , closed - 关闭',
`OBJECT_NO` varchar(25) NOT NULL COMMENT '对象号',
`UPDATE_TIME` timestamp NOT NULL COMMENT '修改时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`VERSION` varchar(10) NOT NULL COMMENT '版本号',
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `UQ_ACC_NO` (`ACCOUNT_NO` ASC),
INDEX `INX_OBJ_NO` (`OBJECT_NO` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账户表';

CREATE TABLE ` AC_TRANSACTION` (
`ID` numeric NOT NULL COMMENT '主键',
`COMMAND_NO` varchar(50) NOT NULL COMMENT '外部指令序号，外部指令凭证，判重(可使用UUID或交易号)',
`COMMAND_TYPE` char(1) NOT NULL COMMENT '指令类型, transfer - 转账, freeze - 冻结, unfreeze - 解冻, error - 错误记录',
`SORT_NUM` int NOT NULL COMMENT '序号,指令集内部顺序',
`TRANSACTION_CODE` varchar(50) NOT NULL COMMENT '事务凭证码，返回的唯一指令流水',
`FROM_ACCOUNT_NO` varchar(25) NOT NULL COMMENT '转出账户号',
`TO_ACCOUNT_NO` varchar(25) NOT NULL COMMENT '转入账户号',
`AMOUNT` numeric(20,0) NOT NULL COMMENT '交易金额',
`CURRENCY` varchar(8) NOT NULL COMMENT '币种',
`TRANSFER_TYPE` varchar(10) NOT NULL COMMENT '转账类型',
`PRODUCT_CODE` varchar(10) NOT NULL COMMENT '产品码',
`BUSINESS_CODE` varchar(10) NOT NULL COMMENT '业务码',
`TRADE_NO` varchar(50) NOT NULL COMMENT '交易流水号',
`TRADE_TIME` timestamp NOT NULL COMMENT '交易时间',
`OUT_TRADE_NO` varchar(50) NULL COMMENT '外部订单号',
`RESULT_CODE` varchar(10) NOT NULL COMMENT '结果码',
`BOOKKEEPING CODER` varchar(10) NOT NULL COMMENT '记账码',
`NOTE` varchar(255) NULL COMMENT '事务备注',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`VERSION` varchar(10) NOT NULL COMMENT '版本号',
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `UQ_COMMAND_NO` (`COMMAND_NO` ASC),
INDEX `INX_TRADE_NO` (`TRADE_NO` ASC),
INDEX `INX_TRANSACTION_CTIME` (`CREATE_TIME` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '记账凭证表';

CREATE TABLE `AC_SEQUENTIAL ` (
`ID` numeric NOT NULL COMMENT '主键',
`TRANSACTION_ID` varchar(255) NOT NULL COMMENT '事务ID',
`ACCOUNT_NO` varchar(30) NOT NULL COMMENT '账户号',
`BALANCE` varchar(20) NOT NULL COMMENT '本期余额',
`PRE_BALANCE` varchar(20) NOT NULL COMMENT '期初余额',
`CREDIT_AMOUNT` varchar(20) NOT NULL COMMENT '贷记金额',
`DEBIT_AMOUNT` varchar(20) NOT NULL COMMENT '借记金额',
`OPPOSITE_ACC_NO` varchar(30) NOT NULL COMMENT '对端账户号',
`CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`VERSION` varchar(10) NOT NULL COMMENT '版本号',
PRIMARY KEY (`ID`) ,
UNIQUE INDEX `UQ_TRAN_ID_ACC_NO` (`TRANSACTION_ID` ASC, `ACCOUNT_NO` ASC),
INDEX `INX_SEQUENTIAL_CTIME` (`CREATED_TIME` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '账务流水表';

